// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxuCO3x9L3HuIdAZkHa4YNl7xFXBbToGc',
    appId: '1:587328776002:web:785f96eaac60c91ed6cadb',
    messagingSenderId: '587328776002',
    projectId: 'gathery-2b199',
    authDomain: 'gathery-2b199.firebaseapp.com',
    databaseURL: 'https://gathery-2b199-default-rtdb.firebaseio.com',
    storageBucket: 'gathery-2b199.appspot.com',
    measurementId: 'G-PD0FPZNJ9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPTTaZAhUAqK42I9xpDlixS19Y3ruTnn0',
    appId: '1:587328776002:android:290be63786f50d09d6cadb',
    messagingSenderId: '587328776002',
    projectId: 'gathery-2b199',
    databaseURL: 'https://gathery-2b199-default-rtdb.firebaseio.com',
    storageBucket: 'gathery-2b199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_5uoifapuy8-w0ZiJyWHWgg8amEHAWk',
    appId: '1:587328776002:ios:501d8c6054d409d5d6cadb',
    messagingSenderId: '587328776002',
    projectId: 'gathery-2b199',
    databaseURL: 'https://gathery-2b199-default-rtdb.firebaseio.com',
    storageBucket: 'gathery-2b199.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw_5uoifapuy8-w0ZiJyWHWgg8amEHAWk',
    appId: '1:587328776002:ios:501d8c6054d409d5d6cadb',
    messagingSenderId: '587328776002',
    projectId: 'gathery-2b199',
    databaseURL: 'https://gathery-2b199-default-rtdb.firebaseio.com',
    storageBucket: 'gathery-2b199.appspot.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxuCO3x9L3HuIdAZkHa4YNl7xFXBbToGc',
    appId: '1:587328776002:web:35bcc16c977e690bd6cadb',
    messagingSenderId: '587328776002',
    projectId: 'gathery-2b199',
    authDomain: 'gathery-2b199.firebaseapp.com',
    databaseURL: 'https://gathery-2b199-default-rtdb.firebaseio.com',
    storageBucket: 'gathery-2b199.appspot.com',
    measurementId: 'G-2KKPCJWLGS',
  );

}